### ISSUE TITLE
Feature request: auto update server

### ISSUE THREAD

**Issue by jwgit9** [overlord-bot/Overlord#71]
**Is your feature request related to a problem? Please describe.**
Currently, the discord bot does not auto update whenever the main branch of this repository has an update. The server running the bot must be updated manually.

**Describe the solution you'd like**
If possible, it would be great if the server can auto-update whenever the main branch of this repository gets an update.

**Comment by VNA818-RPI** [comment]
This has been implemented on the server. Using Github webhooks, Github will call [https://vna818.com/api/server/manage/update](https://vna818.com/api/server/manage/update) on the server upon every push, when the server receives this request, it will execute a local command to pull and redeploy the bot.

**Comment by VNA818-RPI** [comment]
This has been implemented on the server. Using Github webhooks, Github will call [https://vna818.com/api/server/manage/update](https://vna818.com/api/server/manage/update) on the server upon every push, when the server receives this request, it will execute a local command to pull and redeploy the bot.
