### ISSUE TITLE
Feature request for Blackjack minigame

### ISSUE THREAD

**Issue by jwgit9** [overlord-bot/Overlord#73]
**Is your feature request related to a problem? Please describe.**
The UI of the Blackjack minigame is currently too plain and hard on the eyes. The blackjack game also 

**Describe the solution you'd like**
Several features I want to see implemented:
1. Emojis instead of letters for displaying the card. Ex: 9♥ instead of 9H
2. Sum the total value of the hand for both the player and the dealer. This sum should be updated if more cards are drawn. Ex: A hand of 5♥ 9♣ should have a total of 14.
3. Every time a player !hit, the new hand should be printed. Example before hit: Your cards are: 7D 4S | Example after hit: "You drew 8H \n Your cards are: 7D 4S 8H"
4. Once a blackjack game is started, the game should keep going on multiple rounds, until the player chooses to quit the game. This also means a command to end the blackjack game needs to be created.

**Comment by cstecc** [comment]
1. Done
2.  Done but not outputted to user
3. Done
4.  Im not sure about this whenever you want to start a new game you just do the !blackjack command again instead I could ask after every round if they would like to quit but that is basically the same thing. If I were to just give a new hand after every game is over and they wanted to quit then it would be in the middle of a hand which doesn't really make sense.

**Comment by jwgit9** [comment]
You are right about feature number 4 not being necessary. Other features are verified as completed in #115. Closing issue as completed
