### ISSUE TITLE
Bug: When player wins a blackjack game, the output is incorrect

### ISSUE THREAD

**Issue by jwgit9** [overlord-bot/Overlord#74]
**Describe the bug**
Whenever a player wins the blackjack minigame, the output is "YOU WIN \n YOU LOSE"

**To Reproduce**
Win a blackjack game against the dealer.

**Expected behavior**
Upon win only the "YOU WIN" message is given.

**Screenshots**
![blackjack win bug](https://user-images.githubusercontent.com/39379864/197918032-1da25ff5-86c6-45a5-810f-dd3f99e962b3.png)

**Comment by cstecc** [comment]
Fixed issue
