### ISSUE TITLE
Webcrawler should always parse an integer into credit count

### ISSUE THREAD

**Issue by EggyRepublic** [overlord-bot/Overlord#80]
Sometimes on the catalog website a sentence is added in place of where the credit count goes. The parser should instead always enter an integer into the credit field

**To Reproduce**
scroll down to a course such as "fields and waves I" in the json output

**Incorrect behavior**
credits: 4Contact, Lecture or Lab Hours: 6 contact hours credits

**Expected behavior**
credits: 4

**Comment by jwgit9** [comment]
Closing issue, fixed in PR [86](https://github.com/overlord-bot/Overlord/commit/dddff164d7c1060bcd590dca5e8a3a4f3a767072)
